//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecommerce.protume.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class detallePedido
    {
        public int id { get; set; }
        public Nullable<int> id_pedido { get; set; }
        public Nullable<int> id_detalle_producto { get; set; }
        public Nullable<int> cantidad { get; set; }
    
        public virtual detalleProducto detalleProducto { get; set; }
        public virtual pedido pedido { get; set; }
    }
}
