//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecommerce.protume.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalleProducto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public detalleProducto()
        {
            this.detallePedido = new HashSet<detallePedido>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_producto { get; set; }
        public Nullable<int> id_proveedor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detallePedido> detallePedido { get; set; }
        public virtual producto producto { get; set; }
        public virtual proveedor proveedor { get; set; }
    }
}
